from __future__ import annotations


MAT_WIDTH_INCHES = 24.0
MAT_HEIGHT_INCHES = 18.0
MM_PER_INCH = 25.4
MAT_WIDTH_MM = MAT_WIDTH_INCHES * MM_PER_INCH
MAT_HEIGHT_MM = MAT_HEIGHT_INCHES * MM_PER_INCH
RECTIFIED_PIXELS_PER_INCH = 60
RECTIFIED_WIDTH_PX = int(MAT_WIDTH_INCHES * RECTIFIED_PIXELS_PER_INCH)
RECTIFIED_HEIGHT_PX = int(MAT_HEIGHT_INCHES * RECTIFIED_PIXELS_PER_INCH)
SCAN_MAT_GEOMETRY_VERSION = "scan_mat_geometry_v1"
SCAN_MAT_HOMOGRAPHY_VERSION = "opencv_perspective_outer_boundary_v1"
